import { resolve, join } from "node:path";
import { existsSync, unlinkSync, rmdirSync, readdirSync } from "node:fs";

export interface UninstallFremiConfigReport {
  action: "removed" | "not-found" | "kept-non-empty";
  errors: string[];
}

/**
 * Removes <target>/.fremi/config.yaml (generated by `fremi install`). If the
 * .fremi/ directory ends up empty after removing the config, it is also
 * removed. Any other files the user placed inside .fremi/ are preserved.
 */
export async function uninstallFremiConfig(
  targetPath: string,
): Promise<UninstallFremiConfigReport> {
  const fremiDir = resolve(targetPath, ".fremi");
  const configPath = join(fremiDir, "config.yaml");

  if (!existsSync(configPath)) {
    return { action: "not-found", errors: [] };
  }

  try {
    unlinkSync(configPath);
  } catch (err) {
    return {
      action: "not-found",
      errors: [`Failed to remove ${configPath}: ${(err as Error).message}`],
    };
  }

  // Remove the .fremi/ dir only if empty
  try {
    if (existsSync(fremiDir) && readdirSync(fremiDir).length === 0) {
      rmdirSync(fremiDir);
      return { action: "removed", errors: [] };
    }
  } catch {
    // fall through
  }

  return { action: "kept-non-empty", errors: [] };
}
